### ISSUE TITLE
Is the Router protocol exactly a router?

### ISSUE THREAD

**Issue by serhiikrivtsov** [essentialdevelopercom/quiz-app#4]
Hi @caiozullo  and @mapostolakis.
You have correctly used dependency inversion between the `Router` and the `Flow`, as result, the `Flow` doesn't know anything about a concrete implementation of the `Router`. I believe that a protocol used to implement dependency inversion, cause it also belongs to a higher-level module, shouldn't depend on a lower-level module even with names that were used. _Higher-level module should be architected in a way how it can be used and not who will use it_. It gives us a wider reusability of this module.
In our situation, because of the `Router` name, you have used for the protocol, the `Flow` forces this object to be a router. But in some cases, an implementation of the `Router` protocol may not be exactly a router. The QuizeApp can have a UI with only one screen (for example, a table view in which each row will represent a question with appropriate answers, and a result will be shown in the last row), then we do not exactly need any router.

So, in my opinion, this `Router` protocol really looks like it should be just a delegate of the `Flow` class. What do you think, guys?

**Comment by serhiikrivtsov** [comment]
And one more thing, I guess, that exactly because of this, we have some naming confuses.
In the `Flow` class we have such methods: `routeToQuestion(at: Int)`, and `routeToQuestion(after:)` and I belive, that they should be `flowTo...`. In the `FlowTest` all the tests sound like they are testing a router and not a flow. For example `test_start_withNoQuestions_doesNotRouteToQuestion()` I believe should be `test_start_withNoQuestions_doesNotFlowToQuestion()`.

**Comment by caiozullo** [comment]
@serhiikrivtsov I definitely agree with you! That name seems wrong indeed. We started discussing this in the architecture overview video and we thought there was a missing layer where the Router could live. We've also had the same conversation with other viewers and I suggested renaming it to FlowDelegate (or FlowHandler? FlowListener? FlowObserver?).

This was planned for next videos seasons, but I'm thinking about changing it now and maybe record a separate video about it. Do you agree with FlowDelegate for the name?

**Comment by serhiikrivtsov** [comment]
@caiozullo, I guess, the `FlowDelegate` name is ok.

**Comment by caiozullo** [comment]
The `Router` protocol was replaced with a `QuizDelegate` protocol ✅
